title:             C. Foyer
email:             christophe@cfoyer.com
description:       Updates on my projects, activities, and more!
author:            Christophe Foyer
baseurl:           "/blog"
url:               "http://www.cfoyer.com"

# Social Profiles
github_username:   Christophe-Foyer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
